# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-02 10:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=20)),
                ('pincode_init', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=40)),
                ('doctor_names', models.TextField()),
                ('visiting_charges', models.IntegerField()),
                ('cabin_charge', models.IntegerField()),
                ('cabin_empty', models.IntegerField()),
                ('bed_general_charge', models.IntegerField()),
                ('bed_general_empty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='doctors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=50)),
                ('hospital_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultancy.department')),
            ],
        ),
        migrations.CreateModel(
            name='hospital',
            fields=[
                ('hospital_id', models.CharField(max_length=20, primary_key='True', serialize=False)),
                ('pincode', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('hospital_name', models.CharField(max_length=100)),
                ('hospital_rating', models.IntegerField()),
                ('city_or_town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultancy.city')),
                ('department_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultancy.department')),
                ('department_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_requests_created', to='consultancy.department')),
            ],
        ),
        migrations.CreateModel(
            name='hospital_price_slab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slab_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='state',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='hospital',
            name='price_slab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultancy.hospital_price_slab'),
        ),
    ]
